from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from app.core.security import get_current_user, CurrentUser, is_mock_mode
from firebase_admin import auth as firebase_auth

router = APIRouter(prefix="/auth", tags=["Authentication & Access Control"])


class TokenVerifyRequest(BaseModel):
    id_token: str


class AuthResponse(BaseModel):
    uid: str
    email: str
    name: str
    role: str
    badge_id: str
    department: str
    is_demo: bool


@router.get("/me", response_model=AuthResponse, summary="Get current logged-in officer profile")
async def get_me(user: CurrentUser = Depends(get_current_user)):
    """
    Returns authenticated government officer identity verified via Firebase Auth ID Token.
    """
    return AuthResponse(
        uid=user.uid,
        email=user.email,
        name=user.name,
        role=user.role,
        badge_id=user.badge_id,
        department=user.department,
        is_demo=user.is_demo
    )


@router.post("/verify-token", response_model=AuthResponse, summary="Verify Firebase ID Token")
async def verify_token(req: TokenVerifyRequest):
    """
    Validates a Firebase ID Token generated by the frontend Firebase SDK.
    Verifies signature and decodes user profile claims.
    """
    if req.id_token.startswith("demo-") or is_mock_mode():
        return AuthResponse(
            uid="USR-ADMIN-DEMO",
            email="admin.officer@health.gov.in",
            name="Dr. Arvind Rao",
            role="Chief Medical Officer",
            badge_id="GOV-DELHI-001",
            department="Ministry of Health & Family Welfare",
            is_demo=True
        )

    try:
        decoded_token = firebase_auth.verify_id_token(req.id_token)
        uid = decoded_token.get("uid", "")
        email = decoded_token.get("email", "")
        name = decoded_token.get("name", email.split("@")[0].title() if email else "Officer")
        role = decoded_token.get("role", "Government Administrator")
        department = decoded_token.get("department", "Ministry of Health")
        badge_id = decoded_token.get("badge_id", f"GOV-{uid[:6]}")

        return AuthResponse(
            uid=uid,
            email=email,
            name=name,
            role=role,
            badge_id=badge_id,
            department=department,
            is_demo=False
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid Firebase ID token: {str(e)}"
        )


@router.post("/demo-session", response_model=dict, summary="Generate development session")
async def demo_session():
    """
    Convenience endpoint for local development testing without live Google Firebase credentials.
    """
    return {
        "access_token": "demo-admin-token-2026",
        "token_type": "bearer",
        "user": {
            "uid": "USR-ADMIN-DEV",
            "email": "admin.officer@health.gov.in",
            "name": "Dr. Arvind Rao",
            "role": "Chief Medical Officer",
            "badge_id": "GOV-DELHI-001",
            "department": "Ministry of Health & Family Welfare",
            "is_demo": True
        }
    }
